version: '3.2'

services:
  nginx:
    image: nginx
    ports: ['3000:3000', '8086:8086']
    restart: always
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/priv.cert.pem:/etc/ssl/cert.pem:ro
      - /etc/priv.key.pem:/etc/ssl/key.pem:ro

  influxdb:
    build: influxdb:lastest
    env_file: configuration.env
    ports:
      - '8086:8086'
      - '8083:8083'
      - '25826:25826/udp'
    volumes:
      - influxdb_data:/var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./types.db:/usr/share/collectd/types.db:ro

volumes:
  influxdb_data: {}