version: '3.2'

services:
  collectd:
    image: fr3nd/collectd
    privileged: true
    network_mode: host
    volumes:
      - /proc:/mnt/proc:ro
      - ./collectd.conf:/etc/collectd/collectd.conf
  influxdb:
    build: influxdb
    env_file: configuration.env
    ports:
      - '8086:8086'
      - '8083:8083'
      - '25826:25826/udp'
    volumes:
      - influxdb_data:/var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./types.db:/usr/share/collectd/types.db:ro
  grafana:
    build: grafana
    env_file: configuration.env
    links:
      - influxdb
      - graphite
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
  
  graphite:
    image: sitespeedio/graphite:1.0.2-2-b
    ports:
    - "2003:2003"
    - "8080:80"
    restart: always
    volumes:
        - whisper:/opt/graphite/storage/whisper
        # In production you should configure/map these to your container
        # Download from https://github.com/sitespeedio/sitespeed.io/tree/master/docker/graphite
        #- ./graphite/graphite.db:/opt/graphite/storage/graphite.db
        #- ./graphite/conf/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        #- ./graphite/conf/storage-aggregation.conf:/opt/graphite/conf/storage-aggregation.conf
        #- ./graphite/conf/carbon.conf:/opt/graphite/conf/carbon.conf

  sitespeed.io:
    image: sitespeedio/sitespeed.io
    command: -V
    shm_size: 1g
    volumes:
    - /home/osboxes/sitespeed-result/:/sitespeed.io/sitespeed-result

  grafana-setup:
    image: sitespeedio/grafana-bootstrap:7.5
    env_file: configuration.env
    links:
     - grafana


volumes:
  grafana_data: {}
  influxdb_data: {}
  whisper: {}
